version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123